# default KDE build env
include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-linux.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-freebsd.yml

# custom builds
build_local_ubuntu_2004_neon:
  stage: build
  image: ubuntu:20.04
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - echo "Installing dependencies."
    - apt update
    - apt install -y apt-utils
    - apt install -y gnupg wget
    - wget -qO - http://archive.neon.kde.org/public.key | apt-key add -
    - echo "deb http://archive.neon.kde.org/user focal main" >> /etc/apt/sources.list
    - echo "deb-src http://archive.neon.kde.org/user focal main" >> /etc/apt/sources.list
    - sed -i -- 's/#[ ]*deb-src/deb-src/g' /etc/apt/sources.list
    - apt update
    - apt install -y apt-utils eatmydata
    - eatmydata apt build-dep -y kmymoney
    - eatmydata apt install -y qt5-default libsqlcipher-dev libqt5sql5-sqlite qtbase5-private-dev ninja-build

  script:
    - echo "Building."
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
    - ninja

build_local_ubuntu_2110:
  stage: build
  image: ubuntu:21.10
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - echo "Installing dependencies."
    - apt update
    - sed -i -- 's/#[ ]*deb-src/deb-src/g' /etc/apt/sources.list
    - apt update
    - apt install -y apt-utils eatmydata
    - eatmydata apt build-dep -y kmymoney
    - eatmydata apt install -y libsqlcipher-dev libqt5sql5-sqlite qtbase5-private-dev ninja-build

  script:
    - echo "Building."
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
    - ninja
